name: Markdown Checks

on:
  pull_request:
    branches:
      - main

jobs:
  markdown_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install -g markdownlint-cli markdown-spellcheck markdown-link-check

      - name: Run Markdown linter
        if: always()
        run: |
          npx markdownlint '**/*.md' --config .markdownlint.yaml --ignore 'node_modules/**' | tee markdownlint.txt
          if [ $? -ne 0 ]; then
            gh pr comment ${{ github.event.pull_request.number }} -F markdownlint.txt
            return 1
          fi

      - name: Run spell checker
        if: always()
        run: |
          npx markdown-spellcheck '**/*.md' --en-us -r -x -a | tee markdown-spellcheck.txt
          if [ $? -ne 0 ]; then
            gh pr comment ${{ github.event.pull_request.number }} -F markdown-spellcheck.txt
            return 1
          fi

      - name: Run link checker
        if: always()
        run: |
          find . -name "*.md" -not -path "./node_modules/*" -not -path "./.github/*" -exec npx markdown-link-check -q {} + | tee markdown-link-check.txt
          if [ -s markdown-link-check.txt ]; then
            gh pr comment ${{ github.event.pull_request.number }} -F markdown-link-check.txt
            return 1
          fi
